"""Regression coverage for GitHub #1-18 and #63, with the actual webview bundle."""
from playwright.sync_api import expect
from headless_browser import headless_browser

with headless_browser() as browser:
    page = browser.new_page(viewport={'width': 1100, 'height': 800})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    def fresh(query=''):
        page.goto('http://127.0.0.1:4173/dev/preview.html?mode=agent'+query)
        page.wait_for_load_state('networkidle')
        page.locator('#harness').evaluate('(e)=>e.remove()')
        return page.locator('.composer > textarea')
    def emit(msg):
        page.evaluate('m=>window.dispatchEvent(new MessageEvent("message", {data:m}))', msg)
    def sent():
        return page.evaluate('(window.__hostMessages||[]).filter(m=>m.kind==="send")')
    text = fresh()
    text.fill(' \n ')
    expect(page.locator('.send')).to_have_count(0)
    expect(page.locator('.voice')).to_have_attribute('title', 'Spracheinstellungen öffnen')
    text.press('Enter')
    assert sent() == []
    text.fill('日本語')
    text.dispatch_event('keydown', {'key':'Enter', 'isComposing':True})
    assert sent() == []
    expect(text).to_have_value('日本語')
    text.fill('/review')
    expect(page.locator('.suggest-popup')).to_be_visible()
    text.press('Enter')
    expect(text).to_have_value('/review ')
    assert sent() == []
    text.press('Enter')
    assert sent()[-1]['text'] == '/review', sent()
    emit({'kind':'busy','running':False})
    text.press('ArrowUp')
    expect(text).to_have_value('/review')
    text.press('ArrowDown')
    expect(text).to_have_value('')
    text.fill('Frag (@claude')
    expect(page.locator('.suggest-popup')).to_be_visible()
    text.press('Tab')
    assert '@claude:' in text.input_value()
    text.fill('')
    long_text = '\n'.join('Zeile '+str(n) for n in range(30))
    text.evaluate('(e,t)=>{const d=new DataTransfer();d.setData("text/plain",t);e.dispatchEvent(new ClipboardEvent("paste",{clipboardData:d,bubbles:true,cancelable:true}));}',long_text)
    expect(page.locator('.cx-paste-edit')).to_have_value(long_text)
    page.get_by_role('button', name='Eingefügten Text entfernen').click()
    expect(page.locator('.cx-paste-edit')).to_have_count(0)
    page.get_by_role('button', name='Rückgängig', exact=True).click()
    expect(page.locator('.cx-paste-edit')).to_have_value(long_text)
    # Clipboard images take the host path, not the text-paste path.
    text.evaluate('''e=>{const d=new DataTransfer();d.items.add(new File([new Uint8Array([137,80,78,71])],"shot.png",{type:"image/png"}));e.dispatchEvent(new ClipboardEvent("paste",{clipboardData:d,bubbles:true,cancelable:true}));}''')
    page.wait_for_function('(window.__hostMessages||[]).some(m=>m.kind==="saveAttachmentData" && m.name==="shot.png")')
    text = fresh()
    text.fill('vor nach')
    text.evaluate('e=>e.setSelectionRange(4,4)')
    text.evaluate('e=>{const d=new DataTransfer();d.setData("text/plain","URL ");e.dispatchEvent(new DragEvent("drop",{dataTransfer:d,bubbles:true,cancelable:true}));}')
    expect(text).to_have_value('vor URL nach')
    emit({'kind':'attachments','paths':['/demo/file'+str(n)+'.txt' for n in range(20)]})
    expect(page.locator('.attachment-row')).to_have_count(20)
    assert page.locator('.attachment-strip').bounding_box()['height'] <= 145
    assert text.bounding_box()['y']+text.bounding_box()['height'] < 800
    text.fill(('lange Zeile\n'*35)+'Ende')
    text.press('End')
    text.press('Control+End')
    before=text.evaluate('e=>({h:e.offsetHeight,y:e.getBoundingClientRect().y,scroll:e.scrollTop})')
    text.press('x')
    after=text.evaluate('e=>({h:e.offsetHeight,y:e.getBoundingClientRect().y,scroll:e.scrollTop})')
    assert before['h']==after['h'] and before['y']==after['y'],(before,after)
    text = fresh('&scenario=conversation')
    page.locator('.model-btn').click()
    page.locator('.cx-rz-title').click()
    menu=page.get_by_role('menu',name='Modell auswählen')
    expect(menu.get_by_role('group',name='Grok · studio').get_by_role('menuitemradio')).to_be_disabled()
    page.keyboard.press('Escape')
    expect(page.locator('.cx-rz-slider')).to_be_visible()
    slider=page.get_by_role('slider',name='Reasoning')
    box=slider.bounding_box()
    page.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2)
    page.mouse.down()
    page.mouse.move(box['x']+box['width']+60,box['y']+box['height']/2)
    page.mouse.up()
    expect(slider).to_have_value('4')
    page.keyboard.press('Escape')
    # Inline editor obeys Cmd+Enter too.
    emit({'kind':'appSettings','values':{'composer.senden':'cmd-enter'}})
    edit=page.get_by_role('button', name='Nachricht bearbeiten').first
    edit.click()
    inline=page.locator('.cx-c-edit-input')
    inline.fill('Bearbeitete Nachricht')
    inline.press('Enter')
    expect(inline).to_be_visible()
    assert not page.evaluate('(window.__hostMessages||[]).some(m=>m.kind==="editMessage")')
    inline.press('Meta+Enter')
    page.wait_for_function('(window.__hostMessages||[]).some(m=>m.kind==="editMessage")')
    # #64: mode switches preserve both the prompt and image settings.
    text=fresh()
    text.fill('Ein Bild mit Bergen und See')
    text.press('Meta+i')
    page.get_by_title('Seitenverhältnis', exact=True).click()
    page.get_by_role('menuitemradio', name='16:9', exact=True).click()
    page.get_by_title('Anzahl der Bilder', exact=True).click()
    page.locator('.cx-img-count').get_by_role('menuitemradio', name='3', exact=True).click()
    text.focus()
    text.press('Escape')
    expect(page.locator('.composer.is-image')).to_have_count(0)
    expect(text).to_have_value('Ein Bild mit Bergen und See')
    text.press('Meta+i')
    expect(page.get_by_title('Seitenverhältnis', exact=True)).to_contain_text('16:9')
    expect(page.get_by_title('Anzahl der Bilder', exact=True)).to_contain_text('3')
    expect(text).to_have_value('Ein Bild mit Bergen und See')
    text=fresh('&accounts=empty')
    page.get_by_title('Hinzufügen',exact=True).click()
    expect(page.get_by_role('menuitem',name='Bild erstellen')).to_be_disabled()
    expect(page.get_by_role('menuitem',name='Bild erstellen')).to_have_attribute('title', 'Erfordert ein verfügbares ChatGPT- oder Grok-Konto')
    page.keyboard.press('Escape')
    text.press('Meta+i')
    expect(page.locator('.composer.is-image')).to_have_count(0)
    # The Codex-shaped voice controls open real setup and retain the draft.
    text = fresh()
    text.fill('Diesen Entwurf nach der Spracheinrichtung behalten.')
    emit({'kind':'attachments','paths':['/demo/notizen.txt']})
    page.get_by_role('button',name='Diktat einrichten',exact=True).click()
    expect(page.get_by_role('heading',name='Stimme')).to_be_visible()
    page.get_by_role('button',name='Zurück zur App',exact=True).click()
    expect(page.locator('.composer > textarea')).to_have_value('Diesen Entwurf nach der Spracheinrichtung behalten.')
    expect(page.locator('.attachment-row')).to_have_count(1)
    assert sent() == []
    assert errors==[],errors
    print('Composer issues: clipboard, IME, suggestions, undo, history, drop, sizing, accounts, slider, inline editing, image availability and voice-setup draft preservation passed.')
